### PR TITLE
explictly use the change action for udevadm trigger

### PR DESCRIPTION
**Pull request by nexecook**
centos 6 defaults to --action=add
https://lists.ubuntu.com/archives/ubuntu-devel/2009-January/027260.html
https://bugzilla.redhat.com/show_bug.cgi?id=570355

### CODE REVIEW

**Comment by jhoblitt** [comment]
It might be easiest to just drop ruby < 2 from the travis matrix.

**Comment by nexecook** [comment]
I can open a separate pr for fixing travis if you want^^

**Comment by jhoblitt** [comment]
@nexecook No, this is great.  Thanks!

**Comment by jhoblitt** [comment]
Released as part of 2.2.0.

**Pull request merged**
