### PR TITLE
compatibilty rhel 9 / centos 9

### PR DESCRIPTION
**Pull request by janfickler**

### CODE REVIEW

**Comment by jhoblitt** [comment]
@janfickler Looks like CI is broken in this repo. Have you tested this module as working on EL9?

**Comment by janfickler** [comment]
it worked :-)

**Comment by jhoblitt** [comment]
> it worked :-)

OK ;)

**Comment by XMol** [comment]
Sadly, `metadata.json` was not updated accordingly. 🙁

**Pull request merged**
